# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---

- name: Perform PeerTube installation tasks
  block:
    - name: Validate PeerTube configuration
      when: peertube_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"

    - name: Install PeerTube
      when: peertube_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"
  tags:
    - setup-all
    - setup-peertube
    - install-all
    - install-peertube

- name: Perform PeerTube uninstallation tasks
  block:
    - name: Uninstall PeerTube
      when: not peertube_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
  tags:
    - setup-all
    - setup-peertube
